name: Qodana

on:
  push:
    branches: [ qodana ]
    paths:
      - .github/workflows/qodana.yml
  pull_request:
    types: [ opened, synchronize ]
    tags:
      - 'pr-test-*'

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v4.2.5
        with:
          report-dir: docs
      - run: ls -l
      - run: ls -l
        working-directory: qodana
      - run: ls -l
        working-directory: docs
      - name: Count changes
        id: changes
        run: |
          git add -N docs
          echo "::set-output name=count::$(git diff --name-only docs | wc -l)"
      - run: echo ${{ steps.changes.outputs.count }}
      - name: 'Report Push'
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add docs
          git commit -m "Qodana report"
          git push
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
